api_platform:
    mapping:
        paths:
            - '%kernel.project_dir%/src/Entity'
            - '%kernel.project_dir%/src/TripBundle/Entity'

    patch_formats:
        json: [ 'application/merge-patch+json' ]
    path_segment_name_generator: api_platform.path_segment_name_generator.dash
    swagger:
        versions: [ 3 ]
    formats:
        jsonld: [ 'application/ld+json' ]
        jsonhal: [ 'application/hal+json' ]
        jsonapi: [ 'application/vnd.api+json' ]
        json: [ 'application/json' ]
        xml: [ 'application/xml', 'text/xml' ]
        html: [ 'text/html' ]

#    securityDefinitions:
#        BasicAuth:
#            type: http
#            scheme: basic
    defaults:
        security:
            -   BasicAuth: [ ]