version: '3.9'
services:
    db:
        container_name: db
        image: mysql:8.0.22
        command: ["--default-authentication-plugin=mysql_native_password"]
        ports:
            - "3307:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: symfony
            MYSQL_USER: symfony
            MYSQL_PASSWORD: symfony

    php:
        container_name: php-fpm
        build:
            context: ./docker/php-fpm
            args:
                ENABLE_PHP_XDEBUG: 1
        environment:
            PHP_IDE_CONFIG: serverName=CliXdebug
        ports:
            - "9000:9001"
        volumes:
            - dicache:/var/www/symfony/var/cache
            - bundle-test-dicache:/var/www/symfony/TripBundle/Tests/Api/cache
            - vendor:/var/www/symfony/vendor
            - ./:/var/www/symfony:cached
            - ./var/log:/var/www/symfony/var/log:cached
        depends_on:
            - db

    nginx:
        container_name: nginx
        build: ./docker/nginx
        ports:
            - "80:80"
        depends_on:
            - php
        volumes:
            - ./logs/nginx:/var/log/nginx:cached
            - ./:/var/www/symfony:cached

volumes:
    dicache:
    bundle-test-dicache:
    vendor: