<?php
/**
 * AccountsApiInterface
 * PHP version 7.1.3
 *
 * @category Class
 * @package  TripBundle
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Trips
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace TripBundle\Api;

use Symfony\Component\HttpFoundation\File\UploadedFile;
use TripBundle\Model\Account;
use TripBundle\Model\AccountCreate;
use TripBundle\Model\AccountUpdate;
use TripBundle\Model\DefaultResponse;

/**
 * AccountsApiInterface Interface Doc Comment
 *
 * @category Interface
 * @package  TripBundle\Api
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */
interface AccountsApiInterface
{

    /**
     * Sets authentication method BearerAuth
     *
     * @param string $value Value of the BearerAuth authentication method.
     *
     * @return void
     */
    public function setBearerAuth($value);

    /**
     * Operation createAccount
     *
     * Create account
     *
     * @param  TripBundle\Model\AccountCreate $accountCreate  Data of new account (required)
     * @param  integer $responseCode     The HTTP response code to return
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return TripBundle\Model\Account
     *
     */
    public function createAccount(AccountCreate $accountCreate, &$responseCode, array &$responseHeaders);

    /**
     * Operation deleteAccount
     *
     * Delete account
     *
     * @param  int $accountId   (required)
     * @param  integer $responseCode     The HTTP response code to return
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return TripBundle\Model\DefaultResponse
     *
     */
    public function deleteAccount($accountId, &$responseCode, array &$responseHeaders);

    /**
     * Operation getAccount
     *
     * Get account information
     *
     * @param  int $accountId   (required)
     * @param  integer $responseCode     The HTTP response code to return
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return TripBundle\Model\Account
     *
     */
    public function getAccount($accountId, &$responseCode, array &$responseHeaders);

    /**
     * Operation updateAccount
     *
     * Update account information
     *
     * @param  int $accountId   (required)
     * @param  TripBundle\Model\AccountUpdate $accountUpdate  Updatable data of account (required)
     * @param  integer $responseCode     The HTTP response code to return
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return TripBundle\Model\Account
     *
     */
    public function updateAccount($accountId, AccountUpdate $accountUpdate, &$responseCode, array &$responseHeaders);
}
