<?php
/**
 * CountriesApiInterface
 * PHP version 7.1.3
 *
 * @category Class
 * @package  TripBundle
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Trips
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace TripBundle\Api;

use Symfony\Component\HttpFoundation\File\UploadedFile;
use TripBundle\Model\Country;
use TripBundle\Model\DefaultResponse;

/**
 * CountriesApiInterface Interface Doc Comment
 *
 * @category Interface
 * @package  TripBundle\Api
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */
interface CountriesApiInterface
{

    /**
     * Sets authentication method BearerAuth
     *
     * @param string $value Value of the BearerAuth authentication method.
     *
     * @return void
     */
    public function setBearerAuth($value);

    /**
     * Operation getCountries
     *
     * Get list of countries
     *
     * @param  integer $responseCode     The HTTP response code to return
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return TripBundle\Model\Country[]
     *
     */
    public function getCountries(&$responseCode, array &$responseHeaders);
}
