security:
    encoders:
        TripBundle\Entity\Account:
            algorithm: auto

    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        trip_account_provider:
            entity:
                class: TripBundle\Entity\Account
                property: username
    firewalls:
        main:
            anonymous: true
            lazy: true

            http_basic:
                provider: trip_account_provider
                realm: Secured Area
