#index:
#    path: /
#    controller: App\Controller\DefaultController::index

redirect_to_doc:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    defaults:
        path: /api
        permanent: true