<?php
/**
 * Filter
 *
 * PHP version 7.1.3
 *
 * @category Class
 * @package  TripBundle\Model
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Trips
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace TripBundle\Model;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\SerializedName;
use TripBundle\Entity\Country;
use TripBundle\Validator\EntityExist;

/**
 * Class representing the Filter model.
 *
 * @package TripBundle\Model
 * @author  OpenAPI Generator team
 */
class Filter 
{
        /**
     * @var \DateTime|null
     * @SerializedName("started_at")
     * @Assert\Date()
     * @Type("DateTime<'Y-m-d'>")
     */
    protected $startedAt;

    /**
     * @var \DateTime|null
     * @SerializedName("finished_at")
     * @Assert\Date()
     * @Type("DateTime<'Y-m-d'>")
     */
    protected $finishedAt;

    /**
     * @var Country
     * @SerializedName("country")
     * @Assert\Type(Country::class)
     * @Type(Country::class)
     * @ORM\ManyToOne(targetEntity=Country::class)
     * @EntityExist(entityClass=Country::class)
     */
    protected $country;

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->startedAt = isset($data['startedAt']) ? $data['startedAt'] : null;
        $this->finishedAt = isset($data['finishedAt']) ? $data['finishedAt'] : null;
        $this->country = isset($data['country']) ? $data['country'] : null;
    }

    /**
     * Gets startedAt.
     *
     * @return \DateTime|null
     */
    public function getStartedAt(): ?\DateTime
    {
        return $this->startedAt;
    }

    /**
     * Sets startedAt.
     *
     * @param \DateTime|null $startedAt
     *
     * @return $this
     */
    public function setStartedAt(\DateTime $startedAt = null)
    {
        $this->startedAt = $startedAt;

        return $this;
    }

    /**
     * Gets finishedAt.
     *
     * @return \DateTime|null
     */
    public function getFinishedAt(): ?\DateTime
    {
        return $this->finishedAt;
    }

    /**
     * Sets finishedAt.
     *
     * @param \DateTime|null $finishedAt
     *
     * @return $this
     */
    public function setFinishedAt(\DateTime $finishedAt = null)
    {
        $this->finishedAt = $finishedAt;

        return $this;
    }

    /**
     * Gets country.
     *
     * @return Country|null
     */
    public function getCountry()
    {
        return $this->country;
    }

    /**
     * Sets country.
     *
     * @param Country|null $country
     *
     * @return $this
     */
    public function setCountry($country = null)
    {
        $this->country = $country;

        return $this;
    }
}


