on:
    push:
        branches:
            - main
            # TODO remove before merge
            - api-platform
    pull_request:
        branches:
            - main
            # TODO remove before merge
            - api-platform
name: Test
env:
    PHP_VERSION_CODECOVERAGE: 7.4.x
    OS_CODE_COVERAGE: ubuntu-latest
jobs:
    test:
        services:
            mysql:
                image: mysql:8
                env:
                    MYSQL_ROOT_PASSWORD: root
                    MYSQL_DATABASE: symfony_test
                ports:
                    - 3306:3306
                options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
        strategy:
            matrix:
                php-version:
                    - 7.4
                    - 8.0
                os:
                    - ubuntu-latest
        runs-on: ${{ matrix.os }}
        steps:
            -   name: Install PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php-version }}
            -   name: Checkout code
                uses: actions/checkout@v2
            -   name: Get composer cache directory
                id: composer-cache
                run: echo "::set-output name=dir::$(composer config cache-files-dir)"
            -   uses: actions/cache@v2
                with:
                    path: ${{ steps.composer-cache.outputs.dir }}
                    key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                    restore-keys: ${{ runner.os }}-composer-
            -   name: Install dependencies
                run: composer install --prefer-dist
            -   name: Full test
                run: make test